package pe.com.petroperu.ad.util;

public enum RolAD
{
  JEFE("JEFE", "ROLE_JEFE"),
  EJECUTOR("EJECUTOR", "ROLE_EJECUTOR"),
  GESTOR("GESTOR CORRESPONDENCIA", "ROLE_GESTOR"),
  ADMINISTRADOR("ADMINISTRADOR FUNCIONAL", "ROLE_ADMINISTRADOR"),
  FISCALIZADOR("FISCALIZADOR", "ROLE_FISCALIZADOR"),
  USUARIO("USUARIO", "ROLE_USUARIO"),
  EXTERNO("EXTERNO", "ROLE_EXTERNO"),
  /*9000004276 - INICIO*/
  RECEPTOR("RECEPTOR DESPACHADO","ROLE_RECEPTOR"),
  P8CEADMIN("P8CEADMINISTRATORS","ROLE_P8CEADMIN"),
  P8PEADMIN("P8PEADMINISTRATORS","ROLE_P8PEADMIN");
  /*9000004276 - FIN*/
  
  public final String ROL;
  public final String ROL_SEGURIDAD;
  
  RolAD(String rolAD, String rolSeguridad) {
    this.ROL = rolAD;
    this.ROL_SEGURIDAD = rolSeguridad;
  }
}
